name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-publish:
    name: Build, Test, Publish (${{ matrix.rid }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: tar.gz
          - os: windows-latest
            rid: win-x64
            ext: zip
          - os: macos-latest
            rid: osx-x64
            ext: tar.gz

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore RagCap.sln

      - name: Build
        run: dotnet build RagCap.sln -c Release --no-restore

      - name: Test
        run: dotnet test RagCap.sln -c Release --no-build --verbosity normal

      - name: Publish CLI (self-contained single-file)
        run: dotnet publish RagCap.CLI/RagCap.CLI.csproj -c Release -f net8.0 -r ${{ matrix.rid }} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=partial -p:InvariantGlobalization=true -o ./artifacts/cli/${{ matrix.rid }}

      - name: Package artifact
        shell: bash
        run: |
          cd artifacts/cli
          name=ragcap-cli-${{ matrix.rid }}
          if [ "${{ matrix.ext }}" = "zip" ]; then
            cd ${{ matrix.rid }} && 7z a -tzip ../$name.zip ./* && cd ..
          else
            tar -C ${{ matrix.rid }} -czf $name.tar.gz .
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragcap-cli-${{ matrix.rid }}
          path: |
            artifacts/cli/ragcap-cli-${{ matrix.rid }}.zip
            artifacts/cli/ragcap-cli-${{ matrix.rid }}.tar.gz
